services:
  db:
    build:
      context: .
      dockerfile: ./DockerfilePG
    ports:
      - "5432:5432"
    networks:
      - app_network
  
  backend:
    build:
      context: .
      dockerfile: ./DockerfileBE
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_network
 
networks:
  app_network:
    driver: bridge